package com.prosthetics;

import com.prosthetics.SyncService;

import android.content.BroadcastReceiver;
import android.content.Context;
import android.content.Intent;
import android.util.Log;

/**
 * This class listens for pending intent triggered by an {@link android.app.AlarmManager} in
 * {@link SocialGathererService}, and starts {@link SyncService}.
 * @author aumar11 and jbanford, based on prior work by 
 * @author Stephen Bell
 * @author Jakub Konka
 * 
 * @version 1.0
 * @see android.content.BroadcastReceiver
 * @see android.content.Intent
 * @see android.app.AlarmManager
 * @see com.location.LocationGathererService
 * @see com.location.SyncService
 */
public class SyncAlarmReceiver extends BroadcastReceiver
{
  /**
   * Tag for use in logging and debugging the output generated by this class.
   */
  public final static String TAG = "SyncAlarmReceiver";

  /**
   * Called when an {@code Intent} is received. This method triggers
   * {@link SyncService}.
   * @param context The {@code Context} in which the receiver is running.
   * @param intent The {@code Intent} being received.
   * @see android.content.Context
   * @see android.content.Intent
   * @see com.location.SyncService
   */
  @Override
  public void onReceive(Context context, Intent intent)
  {
    Log.i(TAG, "Synchronisation with server requested");
    Intent syncIntent = new Intent(context, SyncService.class);
    context.startService(syncIntent);
  }
}